[workspace]
members = [
    "applets/cosmic-applet-audio",
    "applets/cosmic-applet-battery",
    "applets/cosmic-applet-graphics",
    "applets/cosmic-applet-network",
    "applets/cosmic-applet-notifications",
    "applets/cosmic-applet-power",
    "applets/cosmic-applet-workspaces",
    "applets/cosmic-applet-status-area",
    "applets/cosmic-applet-time",
    "applets/cosmic-app-list",
    "applets/cosmic-panel-button",
    "libcosmic-applet",
]

[patch.crates-io]
wayland-protocols = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
wayland-sys = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
wayland-backend = { git = "https://github.com/smithay/wayland-rs", version = "0.1.0-beta.9"}
wayland-scanner = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
wayland-client = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
