[workspace]
members = [
    "applets/cosmic-applet-graphics",
    "applets/cosmic-applet-network",
    "applets/cosmic-applet-notifications",
    "applets/cosmic-applet-power",
    "applets/cosmic-applet-workspaces",
    "applets/cosmic-applet-status-area",
    "applets/cosmic-applet-time",
    "applets/cosmic-app-list",
    "applets/cosmic-panel-button",
]

exclude = [
    "applets/cosmic-applet-audio",
    "applets/cosmic-applet-battery",
]
