[package]
name = "cosmic-applet-power"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
futures-util = "0.3.21"
gtk4 = "0.4.6"
logind-zbus = "3.0.1"
nix = "0.23.1"
once_cell = "1.9.0"
relm4-macros = "0.4.1"
tokio = { version = "1.15.0", features = ["full"] }
zbus = "2.0.1"
cosmic-panel-config = {git = "https://github.com/pop-os/cosmic-panel", features = ["gtk4"]}
