[package]
name = "cosmic-applet-audio"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-or-later"

[dependencies]
futures-util = "0.3.21"
gtk4 = "0.4.6"
once_cell = "1.10.0"
relm4-macros = "0.4.2"
tokio = { version = "1.17.0", features = ["full"] }
libcosmic-widgets = { git = "https://github.com/pop-os/libcosmic", branch = "lucy/widgets" }
