[package]
name = "cosmic-applet-power-battery"
version = "0.1.0"
edition = "2021"

[dependencies]
relm4 = { git = "https://github.com/relm4/relm4", branch = "next", features = ["macros"] }
gtk4 = { git = "https://github.com/gtk-rs/gtk4-rs" }
