[package]
name = "cosmic-applet-workspaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cosmic-panel-config = { git="https://github.com/pop-os/cosmic-panel/", features = ["gtk4"] }
cascade = "1.0.0"
gtk4 = { version = "0.4.5", features = ["v4_4"] }
once_cell = "1.9.0"
pretty_env_logger = "0.4"
anyhow = "1.0.50"
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.4"
rust-embed = "6.3.0"
tokio = { version = "1.16.1", features = ["sync"] }
wayland-client = "0.29.4"
wayland-commons = "0.29.4"
sctk = { package = "smithay-client-toolkit", git = "https://github.com/wash2/client-toolkit.git", default-features = false, features = ["calloop"] }

[build-dependencies]
gio = "0.15.10"
wayland-scanner = "0.29"
